version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: lime_backend
    restart: always
    environment:
      DATABASE_URL: postgres://limeuser:strongpassword@db:5432/limedb
    ports:
      - "8000:8000"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
    container_name: lime_backend
    restart: always
    environment:
      DATABASE_URL: postgres://limeuser:strongpassword@db:5432/limedb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        JWT_SECRET: "dinsuperhemliganyckel"
    container_name: lime_frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  postgres_data:
